Suggest an addition
===================

The more cases Friendly-traceback will include, the more useful
it will be.
If you have used Friendly-traceback and come accross a situation
where it either did not know how to deal with a given exception type,
or could not provide an appropriate explanation, please
`file an issue <https://github.com/aroberge/Friendly-traceback/issues>`_.

Ideally, you should include the code sample that give rise to that
exception and an explanation that would be understandable by
beginners and helpful to them to understand what that exception means.
Please include which version of Python and Friendly-traceback you are
using.

If you have not used Friendly-traceback and would like to see if you
can find some new cases, you can either clone the code repository
or install it from pypi.org (note that the version on pypi.org would
likely not include as many cases as the development version).
Once you have Friendly-traceback on your computer, start its console
from a command line using::

    python -m friendly_traceback

and start writing code like you normally would.

If you want to go beyond simply making a suggestion and wish to
submit code dealing with this case, please consult
:ref:`adding_exception`.
